version: '3.7'
services:
  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - './monitor:/monitor'
    - './db:/db'
    env_file: .env
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
    - './scraper:/scraper'
    - './db:/db'
    env_file: [.env, .env.private]
  redis:
    image: redis